// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdMw8Uncf6FlUvWaUMDytXdy2kr81Bzmc',
    appId: '1:340477293556:android:2d453cbc4e265cf1f9ffa1',
    messagingSenderId: '340477293556',
    projectId: 'brew-todo',
    storageBucket: 'brew-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAhkzwo2vG9OhZNEnFv6_Ud9cHCfSKv-A',
    appId: '1:340477293556:ios:681734abd4fdb829f9ffa1',
    messagingSenderId: '340477293556',
    projectId: 'brew-todo',
    storageBucket: 'brew-todo.appspot.com',
    iosBundleId: 'com.example.brewTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAhkzwo2vG9OhZNEnFv6_Ud9cHCfSKv-A',
    appId: '1:340477293556:ios:681734abd4fdb829f9ffa1',
    messagingSenderId: '340477293556',
    projectId: 'brew-todo',
    storageBucket: 'brew-todo.appspot.com',
    iosBundleId: 'com.example.brewTodo',
  );
}
